name: CI Checks

on: [push, pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  std:
    name: clippy tests, fmt, run tests 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo clippy --tests
      - run: cargo fmt -- --check
      - run: cargo test --tests
  xtensa:
    name: clippy examples & lib, build examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: esp-rs/xtensa-toolchain@v1.5
      - run: cargo +esp clippy --target xtensa-esp32-none-elf -Z build-std=core --examples --lib
      - run: cargo +esp build --release --target xtensa-esp32-none-elf -Z build-std=core --examples
  release:
    if: github.ref_type == 'tag'
    name: create github release from updated tags
    runs-on: ubuntu-latest
    needs: [xtensa, std]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
